//! Turns the Windows app inventory into a Linux reinstall checklist.
//!
//! The reinstall picker's three tiers are all *Windows* answers — a winget ID
//! or a vendor `.exe` link is useless on Ubuntu. This resolves the same list
//! against a curated table instead, and writes a plain Markdown file the user
//! can open on the new machine with nothing installed.
//!
//! Two rules, both load-bearing:
//!
//! * **"Same app" and "alternative" are never blurred.** Telling someone
//!   "Photoshop → GIMP" as though it were the same program is the quiet
//!   dishonesty this product exists to avoid. Alternatives say what is lost.
//! * **No guessing.** Matching is against a human-verified table; anything
//!   absent is reported as having no answer rather than approximated.
//!
//! Resolved on Windows at backup time rather than on Ubuntu at restore time:
//! the result then needs no network and no package-index queries on the far
//! side, and it survives even if `ferry-restore` never runs.

use crate::types::AppEntry;
use crate::ubuntu::apps::{parse_hint, InstallItem};
use anyhow::{Context, Result};
use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct Equivalent {
    windows_name: String,
    /// "same" — the same application, with a Linux build.
    /// "alternative" — a different application that does a similar job.
    /// "none" — no Linux version and no substitute worth vouching for.
    kind: String,
    linux_name: String,
    install: String,
    note: String,
}

fn table() -> Result<Vec<Equivalent>> {
    serde_json::from_str(include_str!("../../../linux-equivalents.json"))
        .context("linux-equivalents.json is malformed")
}

/// Case-insensitive prefix match against the curated key.
///
/// Registry display names carry version and locale suffixes ("Mozilla Firefox
/// (x64 en-US)"), so exact matching would miss nearly everything. Both sides of
/// the comparison are human-verified — the key is written by us, not inferred —
/// so this stays deterministic rather than fuzzy.
fn find<'a>(entries: &'a [Equivalent], app_name: &str) -> Option<&'a Equivalent> {
    let lower = app_name.to_lowercase();
    entries
        .iter()
        .find(|e| lower.starts_with(&e.windows_name.to_lowercase()))
}

fn bullet(out: &mut String, name: &str, e: &Equivalent) {
    out.push_str(&format!("- **{}** → {}\n", name, e.linux_name));
    if !e.install.is_empty() {
        out.push_str(&format!("  - `{}`\n", e.install));
    }
    if !e.note.is_empty() {
        out.push_str(&format!("  - {}\n", e.note));
    }
}

/// Render the checklist. Public for testing; `write_linux_apps` is the caller.
pub fn render(apps: &[AppEntry]) -> Result<String> {
    let entries = table()?;

    let mut same = Vec::new();
    let mut alternative = Vec::new();
    let mut none = Vec::new();
    let mut unknown = Vec::new();

    for app in apps {
        match find(&entries, &app.name) {
            Some(e) if e.kind == "same" => same.push((app, e)),
            Some(e) if e.kind == "alternative" => alternative.push((app, e)),
            Some(e) => none.push((app, e)),
            None => unknown.push(app),
        }
    }

    let mut out = String::new();
    out.push_str("# Your apps on Ubuntu\n\n");
    out.push_str(
        "Generated by Ferry from the apps installed on your Windows PC. Nothing here installs \
         automatically — you choose what you actually want back.\n\n\
         Commands starting with `sudo` go in a terminal (Ctrl+Alt+T).\n\n",
    );

    if !same.is_empty() {
        out.push_str("## Same app, available on Linux\n\n");
        out.push_str("Programs you already use, with a Linux version.\n\n");
        for (app, e) in &same {
            bullet(&mut out, &app.name, e);
        }
        out.push('\n');
    }

    if !alternative.is_empty() {
        out.push_str("## Different app, similar job\n\n");
        out.push_str(
            "These are **not** the same program. They do a similar job, and each note says what \
             you give up.\n\n",
        );
        for (app, e) in &alternative {
            bullet(&mut out, &app.name, e);
        }
        out.push('\n');
    }

    if !none.is_empty() {
        out.push_str("## No Linux version\n\n");
        out.push_str("There is no honest replacement for these.\n\n");
        for (app, e) in &none {
            out.push_str(&format!("- **{}**\n", app.name));
            if !e.note.is_empty() {
                out.push_str(&format!("  - {}\n", e.note));
            }
        }
        out.push('\n');
    }

    if !unknown.is_empty() {
        out.push_str("## Not in Ferry's list\n\n");
        out.push_str(
            "Ferry has no verified answer for these and will not guess — a wrong download link \
             is worse than none. Search Ubuntu's Software app by name, or check the vendor's own \
             site.\n\n",
        );
        for app in &unknown {
            let publisher = app
                .publisher
                .as_deref()
                .filter(|p| !p.is_empty())
                .map(|p| format!(" — {p}"))
                .unwrap_or_default();
            out.push_str(&format!("- {}{}\n", app.name, publisher));
        }
        out.push('\n');
    }

    out.push_str("---\n\n");
    out.push_str(&format!(
        "{} apps found: {} available on Linux, {} with an alternative, {} with no Linux version, \
         {} unlisted.\n",
        apps.len(),
        same.len(),
        alternative.len(),
        none.len(),
        unknown.len()
    ));
    Ok(out)
}

/// The apps `ferry-restore` can install by itself: curated matches whose hint
/// is a plain apt/snap install. Deduplicated by package — Word and Outlook
/// must not become two LibreOffice installs.
pub fn install_list(apps: &[AppEntry]) -> Result<Vec<InstallItem>> {
    let entries = table()?;
    let mut out: Vec<InstallItem> = Vec::new();
    for app in apps {
        let Some(e) = find(&entries, &app.name).filter(|e| e.kind != "none") else {
            continue;
        };
        let Some((manager, packages, classic)) = parse_hint(&e.install) else {
            continue;
        };
        if out.iter().any(|i| i.packages == packages) {
            continue;
        }
        out.push(InstallItem {
            app: app.name.clone(),
            linux_name: e.linux_name.clone(),
            manager,
            packages,
            classic,
            alternative: e.kind == "alternative",
        });
    }
    Ok(out)
}

/// Write `linux-apps.md` (for the user) and `linux-install.json` (for
/// `ferry-restore`'s one-click install) into the backup directory.
pub fn write_linux_apps(backup_dir: &Path, apps: &[AppEntry]) -> Result<()> {
    std::fs::write(backup_dir.join("linux-apps.md"), render(apps)?)
        .context("Could not write linux-apps.md")?;
    std::fs::write(
        backup_dir.join("linux-install.json"),
        serde_json::to_string_pretty(&install_list(apps)?)?,
    )
    .context("Could not write linux-install.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn app(name: &str) -> AppEntry {
        AppEntry {
            name: name.to_string(),
            version: None,
            publisher: None,
            url_info: None,
            tier: 3,
            winget_id: None,
        }
    }

    #[test]
    fn install_list_keeps_only_unattended_installs() {
        let list = super::install_list(&[
            app("Slack"),
            app("Google Chrome"),
            app("Microsoft Word"),
            app("Microsoft Outlook"),
            app("Notepad++"),
            app("Node.js"),
        ])
        .unwrap();
        let names: Vec<&str> = list.iter().map(|i| i.app.as_str()).collect();
        // Chrome is a vendor .deb, Word is "already installed": not automatic.
        assert_eq!(names, ["Slack", "Microsoft Outlook", "Notepad++", "Node.js"]);
        assert!(list[1].alternative && list[2].alternative && !list[0].alternative);
        assert_eq!(list[3].packages, ["nodejs", "npm"]);
    }

    #[test]
    fn curated_table_parses() {
        assert!(!table().unwrap().is_empty());
    }

    #[test]
    fn registry_suffixes_still_match() {
        // Real DisplayName values carry version/locale suffixes.
        let entries = table().unwrap();
        assert_eq!(find(&entries, "Mozilla Firefox (x64 en-US)").unwrap().kind, "same");
    }

    #[test]
    fn same_app_and_alternative_are_never_conflated() {
        // Photoshop has no Linux build. If GIMP were presented as "the same
        // app", the user would find out the hard way after the wipe.
        let entries = table().unwrap();
        assert_eq!(find(&entries, "Adobe Photoshop 2024").unwrap().kind, "alternative");
        assert_eq!(find(&entries, "GIMP 2.10").unwrap().kind, "same");
    }

    #[test]
    fn unlisted_apps_are_reported_not_guessed() {
        let out = render(&[app("Some Obscure Vendor Tool")]).unwrap();
        assert!(out.contains("Not in Ferry's list"));
        assert!(out.contains("Some Obscure Vendor Tool"));
        assert!(out.contains("will not guess"));
    }

    #[test]
    fn sections_are_grouped_by_kind() {
        let out =
            render(&[app("VLC media player"), app("Adobe Photoshop"), app("iTunes")]).unwrap();
        assert!(out.contains("## Same app, available on Linux"));
        assert!(out.contains("## Different app, similar job"));
        assert!(out.contains("## No Linux version"));
    }
}
